import Logo from '@/components/Logo'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen flex flex-col bg-background-primary text-content-primary`}>
        <header className="sticky top-0 z-20 flex items-center px-6 h-24">
          <Logo className='w-6 h-6' />
          <span className='ml-2 font-bold text-xl'>
            Steer AI
          </span>
        </header>

        {children}

      </body>
    </html>
  )
}
